# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Leonids"
license = "GPL-3"
licenselink = "https://github.com/bridouz/hugo-leonids/blob/master/LICENSE.md"
description = "A simple and clean two columns Hugo theme (Ported from a Jekyll Theme) "
source_repo = "https://github.com/bridouz/leonids"
tags = ["leonids", "blog", "responsive", "lightbox"]
features = ["lightbox", "blog"]
min_version = 0.18

[author]
  name = "Justin Bridouz"
  homepage = "https://www.bloguslibrus.fr"

# If porting an existing theme
[original]
  name = "Leonids"
  homepage = "https://renyuanz.github.io/leonids/"
  repo = "https://github.com/renyuanz/leonids"
